# Generated by Django 4.1.7 on 2024-02-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_patient_contact_no_alter_patient_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='password',
            field=models.TextField(blank=True, null=True),
        ),
    ]
