# Generated by Django 4.1.7 on 2024-02-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='username',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='fname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='lname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
