# Generated by Django 4.1.7 on 2024-02-08 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_doctor_username_alter_doctor_fname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profile_picture',
            field=models.ImageField(default='https://tse1.explicit.bing.net/th?id=OIP.M_cxPuULfylrc9mKkOuqGgHaGd&pid=Api&P=0&h=180', upload_to='doctor'),
        ),
    ]
