# Generated by Django 4.1.7 on 2024-02-08 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_doctor_options_alter_doctor_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
