# Generated by Django 4.1.7 on 2024-02-08 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='NewUser',
        ),
    ]
