# Generated by Django 4.1.7 on 2024-02-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_patient_email_alter_newuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='profile_picture',
            field=models.ImageField(default='https://thumbs.dreamstime.com/b/default-avatar-profile-icon-social-media-user-vector-default-avatar-profile-icon-social-media-user-vector-portrait-176194876.jpg', upload_to='patient'),
        ),
    ]
