# Generated by Django 4.1.7 on 2024-03-05 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_event_patient_booked_alter_event_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time_of_booking',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
