# Generated by Django 4.1.7 on 2024-03-08 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_event_time_of_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='hospital_name',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='Hospital_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='hospital_images/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Himgs', to='core.doctor')),
            ],
        ),
    ]
