# Generated by Django 4.1.7 on 2024-03-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_doctor_hospital_name_hospital_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital_image',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
