# Generated by Django 4.1.7 on 2024-03-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=150, null=True)),
                ('contact', models.IntegerField(blank=True, max_length=10, null=True)),
                ('message', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
