# Generated by Django 4.1.7 on 2024-03-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_bookedappoinment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedappoinment',
            name='Patient_contact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookedappoinment',
            name='Patient_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
