# Generated by Django 4.1.7 on 2024-04-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_bookedappoinment_patient_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedappoinment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
