# Generated by Django 4.1.7 on 2024-04-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_bookedappoinment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='c',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='education',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
