# Generated by Django 4.1.7 on 2024-04-11 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_doctor_c_alter_doctor_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='c',
        ),
    ]
