# Generated by Django 4.1.7 on 2024-04-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_doctor_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='hospital_about',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
