# Generated by Django 4.1.7 on 2024-04-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_doctor_hospital_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='government_schemes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('sub_title', models.TextField(blank=True, max_length=1000, null=True)),
                ('Document', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
