# Generated by Django 4.1.7 on 2024-04-12 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_government_schemes'),
    ]

    operations = [
        migrations.AddField(
            model_name='government_schemes',
            name='title_img',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
