# Generated by Django 4.1.7 on 2024-04-12 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_government_schemes_title_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dr_Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('title_img', models.FileField(blank=True, null=True, upload_to='')),
                ('sub_title', models.TextField(blank=True, max_length=1000, null=True)),
                ('Document', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Dr_govScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('title_img', models.FileField(blank=True, null=True, upload_to='')),
                ('sub_title', models.TextField(blank=True, max_length=1000, null=True)),
                ('Document', models.FileField(blank=True, null=True, upload_to='')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drGov', to='core.doctor')),
            ],
        ),
    ]
