# Generated by Django 4.1.7 on 2024-04-12 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_dr_insurance_dr_govscheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='dr_insurance',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='drInsurance', to='core.doctor'),
            preserve_default=False,
        ),
    ]
