# Generated by Django 4.1.7 on 2024-04-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_dr_insurance_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profile_picture',
            field=models.ImageField(default='doctor\\defaultPicture.png', upload_to='doctor'),
        ),
        migrations.AlterField(
            model_name='dr_govscheme',
            name='title_img',
            field=models.FileField(blank=True, default='doctor\\defaultimg.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='government_schemes',
            name='title_img',
            field=models.FileField(blank=True, default='doctor\\defaultimg.jpg', null=True, upload_to=''),
        ),
    ]
