# Generated by Django 4.1.7 on 2024-04-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_doctor_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dr_govscheme',
            name='Document',
            field=models.FileField(blank=True, null=True, upload_to='govschem\\documents'),
        ),
        migrations.AlterField(
            model_name='dr_govscheme',
            name='title_img',
            field=models.FileField(default='govschem\\images\\defaultimg.jpg', upload_to='govschem\\images'),
        ),
        migrations.AlterField(
            model_name='government_schemes',
            name='title_img',
            field=models.FileField(default='govschem\\images\\defaultimg.jpg', upload_to='Government_schemes\\images'),
        ),
    ]
