# Generated by Django 4.1.7 on 2024-04-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alter_dr_govscheme_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dr_govscheme',
            name='Document',
            field=models.FileField(default='govschem\\documents\x08lank.pdf', upload_to='govschem\\documents'),
        ),
        migrations.AlterField(
            model_name='dr_govscheme',
            name='title_img',
            field=models.FileField(default='govschem\\images\\defaultimg.jpeg', upload_to='govschem\\images'),
        ),
        migrations.AlterField(
            model_name='dr_insurance',
            name='Document',
            field=models.FileField(default='insurance\\documents\x08lank.pdf', upload_to='insurance\\documents'),
        ),
        migrations.AlterField(
            model_name='dr_insurance',
            name='title_img',
            field=models.FileField(default='insurance\\images\\defaultimg.jpg', upload_to='insurance\\images'),
        ),
    ]
