# Generated by Django 4.1.7 on 2024-04-21 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_lab_test_alter_doctor_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab_test',
            name='Degree',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
