# Generated by Django 4.1.7 on 2024-04-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_doctor_maplink'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='opdFees',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
