# Generated by Django 4.1.7 on 2024-05-05 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_alter_doctor_user_alter_event_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedbackquestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('sub_title', models.TextField(blank=True, max_length=1000, null=True)),
                ('title_img', models.FileField(default='govschem\\images\\defaultimg.jpg', upload_to='healthEquipment\\images')),
            ],
        ),
        migrations.CreateModel(
            name='feedbackans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorid', models.IntegerField(blank=True, null=True)),
                ('ans', models.CharField(blank=True, max_length=4, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fbans', to='core.feedbackquestion')),
            ],
        ),
    ]
