# Generated by Django 4.1.7 on 2024-05-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_feedbackquestion_healthequipment_feedbackans'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthequipment',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
