# Generated by Django 4.1.7 on 2024-05-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_healthequipment_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='personal_contact',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
