# Generated by Django 4.1.7 on 2024-05-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_doctor_personal_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthequipment',
            name='contact_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
