# Generated by Django 4.1.7 on 2024-05-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_healthequipment_contact_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthequipment',
            old_name='contact_no',
            new_name='contact',
        ),
        migrations.RemoveField(
            model_name='healthequipment',
            name='sub_title',
        ),
        migrations.RemoveField(
            model_name='healthequipment',
            name='title',
        ),
        migrations.RemoveField(
            model_name='healthequipment',
            name='title_img',
        ),
        migrations.AddField(
            model_name='healthequipment',
            name='about_service',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='healthequipment',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='healthequipment',
            name='name_owner',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
