# Generated by Django 4.1.7 on 2024-06-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_rename_contact_no_healthequipment_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='slotDuration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
