# Generated by Django 4.1.7 on 2024-06-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_doctor_slotduration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='slotDuration',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
