# Generated by Django 4.1.7 on 2024-07-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_alter_doctor_slotduration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
