# Generated by Django 4.1.7 on 2024-07-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_alter_doctor_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='license_no',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
