# Generated by Django 4.1.7 on 2024-08-17 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_gov_scheme_doctor_gov_schemes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='gov_schemes',
        ),
        migrations.CreateModel(
            name='dr_scheme_mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dr_mapping', to='core.doctor')),
                ('gov_scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheme_mapping', to='core.gov_scheme')),
            ],
        ),
    ]
