# Generated by Django 4.1.7 on 2024-08-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_remove_doctor_gov_schemes_dr_scheme_mapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dr_scheme_mapping',
            name='gov_scheme',
            field=models.JSONField(default=list),
        ),
    ]
