# Generated by Django 4.1.7 on 2024-08-17 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_alter_dr_scheme_mapping_gov_scheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dr_scheme_mapping',
            name='gov_scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheme_mapping', to='core.gov_scheme'),
        ),
    ]
