# Generated by Django 4.1.7 on 2024-08-19 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_alter_dr_scheme_mapping_gov_scheme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gov_scheme',
            name='description',
        ),
    ]
